### ISSUE TITLE
K8S pods don't reach DNS / Internet

### ISSUE THREAD

**Issue by waleedhammam** [threefoldtech/zos#1108]
WIDS:
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/3953
https://explorer.devnet.grid.tf/api/v1/reservations/workloads/3960

public ip: 185.69.167.122

```
root@failure40-cryptpad-854497f9db-czm87:/persistent-data# apt-get install net-tools
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  net-tools
0 upgraded, 1 newly installed, 0 to remove and 3 not upgraded.
Need to get 248 kB of archives.
After this operation, 1002 kB of additional disk space will be used.
Err:1 http://deb.debian.org/debian buster/main amd64 net-tools amd64 1.60+git20180626.aebd88e-1
  Temporary failure resolving 'deb.debian.org'
E: Failed to fetch http://deb.debian.org/debian/pool/main/n/net-tools/net-tools_1.60+git20180626.aebd88e-1_amd64.deb  Temporary failure resolving 'deb.debian.org'
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

```
k3os-26493 [~]$ kubectl get service
NAME                 TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
kubernetes           ClusterIP   10.43.0.1       <none>        443/TCP    5h24m
cryptpad-failure40   ClusterIP   10.43.216.197   <none>        8080/TCP   5m16s

k3os-26493 [~]$ curl 10.43.216.197:8080
curl: (28) Failed to connect to 10.43.216.197 port 8080: Operation timed out
```
Tried also with ubuntu pod on this cluster and the same error

kubectl apply -f ubuntu.yaml

ubuntu.yaml file: 
```
apiVersion: v1
kind: Pod
metadata:
  name: appname
  namespace: default
  labels:
    app: appname
spec:
  hostname: appname
  containers:
  - name: ubuntu
    image: "ubuntu:18.04"
    command: ["/bin/bash", "-ce", "tail -f /dev/null"]
```
