### ISSUE TITLE
metrics: assets information

### ISSUE THREAD

**Issue by muhamadazmy** [threefoldtech/zos#1117]
From the mindmap here:
https://app.mindmup.com/map/_v2/90ceb3f0346c11ebb8fbcddb6bd8c75c

we need to collect the entire assets of the node in a structured tree:
 example:
```yaml
disks:
  - name:
      model: <>
      size: <>
      ...
cpu:
  - 0:
    ....

nics:
   - 
```
